# Generated by Django 5.0.6 on 2024-06-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_store_custo_last_na_2e448d_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'category_id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['description', 'product_id']},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
