# Generated by Django 5.0.6 on 2024-05-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeitem',
            name='user',
        ),
    ]
