# Generated by Django 5.0.6 on 2024-06-02 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0003_likeitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='likeitem',
            name='like_detail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='like.likeitemdetail'),
        ),
    ]
