# Generated by Django 5.0.6 on 2024-06-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0004_likeitemdetail_likeitem_like_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeitem',
            name='like_detail',
        ),
        migrations.AddField(
            model_name='likeitem',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='LikeItemDetail',
        ),
    ]
